-- ==================================================================
-- ARCHIVO OBSOLETO — NO EJECUTAR
-- ==================================================================
-- Este script crea la tabla USUARIOS (con S) que es diferente
-- de la tabla USUARIO (sin S) definida en 01-tablas-principales.sql.
-- La tabla correcta del sistema es USUARIO (sin S).
--
-- Si se ejecuta este script, generará conflictos con el esquema
-- principal. Está conservado solo como referencia histórica.
-- ==================================================================
