-- ==================================================================
-- ARCHIVO OBSOLETO — NO EJECUTAR
-- ==================================================================
-- Este script creaba secuencias (animales_seq, usuarios_seq, etc.)
-- que ya NO son necesarias porque todas las tablas usan
-- NUMBER GENERATED ALWAYS AS IDENTITY (auto-increment de Oracle 12c+).
--
-- El script correcto para crear el usuario de la BD es:
--   base-de-datos/00-crear-usuario.sql
--
-- El orden correcto de ejecución es el descrito en:
--   base-de-datos/INSTALAR-BASE-DATOS.sql
-- ==================================================================
