-- ==================================================================
-- ARCHIVO OBSOLETO — NO EJECUTAR
-- ==================================================================
-- Usar en su lugar: base-de-datos/esquemas/03-datos-iniciales-usuarios.sql
-- Este archivo tenía hashes bcrypt inválidos (inventados, no generados
-- con PHP) y ha sido reemplazado por el script correcto.
-- ==================================================================
